######################################################################
# Automatically generated by qmake (3.1) Mon Jun 26 09:26:52 2017
######################################################################
QT += core widgets
TEMPLATE = app
TARGET = ExpressionEvaluator
INCLUDEPATH += .
CONFIG +=c++11

# Input
HEADERS += ExpressionEvaluator.h

SOURCES += \
    main.cpp
